from flask import Flask, request, render_template_string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

app = Flask(__name__)

# HTML Template for the GUI
HTML_TEMPLATE = '''
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Major Recommendations</title>
</head>
<body>
  <h2>Enter your preferences and dislikes</h2>
  <form method="POST">
    <label for="likes">What do you like?</label><br>
    <textarea name="likes" rows="4" cols="50"></textarea><br>
    <label for="dislikes">What do you dislike?</label><br>
    <textarea name="dislikes" rows="4" cols="50"></textarea><br>
    <input type="submit" value="Submit">
  </form>
  {% if results %}
    <h2>Recommended Majors:</h2>
    <ul>
    {% for major, similarity in results %}
      <li>{{ major }} (Similarity: {{ similarity }})</li>
    {% endfor %}
    </ul>
  {% endif %}
</body>
</html>
'''

# Ensure NLTK components are downloaded
nltk.download('punkt')
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = word_tokenize(text.lower())
    filtered_words = [word for word in words if word not in stop_words]
    return ' '.join(filtered_words)

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        likes = request.form['likes']
        dislikes = request.form['dislikes']

        # Remove stopwords from likes and dislikes
        preprocessed_likes = remove_stopwords(likes)
        preprocessed_dislikes = remove_stopwords(dislikes)

        # Add the majors data here:
        majors_data = [
        {"major": "Accounting", "introduction": "This practical, future-focused course will give you the financial and business skills you need to build a successful career in accounting. It offers significant exemptions from chartered accounting professional examinations.", "assessment": {"exams": 58, "coursework": 34, "practical": 9}, "modules": ["Business Law", "Economic Principles in a Contemporary Context", "Essential Information and Academic Skills", "Foundations of Financial Accounting", "Introduction to Management Accounting", "Introduction to Managerial Finance", "Management and Professional Development for Accounting and Finance", "Statistics and Data Management", "Applied Management Accounting", "Corporate Finance", "Financial Accounting", "Financial Accounting and Reporting", "Governance and Accountability", "Management Accounting and Decision Making", "Principles of Taxation", "Work Integrated Learning or Cross Cultural Learning and Development*", "Advanced Case Study", "Business Strategy and Technology", "Corporate Reporting Theory and Practice", "Financial Management", "Strategic Management Accounting"]},
        {"major": "Accounting and Business Management", "introduction": "This applied and industry-engaged course gives you the edge in business by combining key management skills with financial expertise and strategic capabilities. You will also gain some exemptions from professional accounting exams.", "assessment": {"exams": 58, "coursework": 34, "practical": 9}, "modules": ["Business Law", "Economic Principles in a Contemporary Context", "Essential Information and Academic Skills", "Foundations of Financial Accounting", "Introduction to Management Accounting", "Introduction to Managerial Finance", "Management and Professional Development for Accounting and Finance", "Statistics and Data Management", "Applied Research Skills in Accounting and Finance", "Elements of Management in Practice", "Management Accounting and Decision Making", "Managing People", "Business Strategy and Technology", "Managing Organisational Change", "Strategic Management Accounting", "Strategic Project (Accounting and Finance)", "Work Integrated Learning (Accounting and Finance) or Cross Cultural Learning and Development*", "Business Strategy and Technology", "Managing Organisational Change", "Strategic Management Accounting", "Strategic Project (Accounting and Finance)", "Work Integrated Learning (Accounting and Finance) or Cross Cultural Learning and Development"]},
        {"major": "Accounting and Finance", "introduction": "This applied and future-focused course balances knowledge and skills in accounting with applied understanding of finance, giving access to a wide range of financial careers. You will also gain some exemptions from professional accounting examinations.", "assessment": {"exams": 58, "coursework": 34, "practical": 9}, "modules": ["Business Law", "Economic Principles in a Contemporary Context", "Essential Information and Academic Skills", "Foundations of Financial Accounting", "Introduction to Management Accounting", "Introduction to Managerial Finance", "Management and Professional Development for Accounting and Finance", "Statistics and Data Management", "Applied Research Skills in Accounting and Finance", "Corporate Finance", "Financial Accounting", "Financial Accounting and Reporting", "Management Accounting and Decision Making", "Business Strategy and Technology", "Financial Management", "Strategic Project (Accounting and Finance)"]},
        {"major": "Aerospace Engineering", "introduction": "Study in the UK's aerospace hub on a course developed with some of the biggest names in engineering.", "assessment": {"exams": 45, "coursework": 50, "practical": 5}, "modules": ["Aerospace Engineering", "Aerospace Thermofluids", "Dynamics Modelling and Simulation", "Engineering Practice 1", "Solid Mechanics Materials and Manufacturing", "Aerospace Systems Design", "Engineering Practice 2", "Engineering Research", "Flight", "Fundamental Aero-Propulsion", "Fundamental Aerodynamics", "Structural Mechanics", "Aerospace Group Design Project", "Engineering Project", "Professionalism for Engineers*", "Aerospace Group Design Project", "Engineering Project", "Professionalism for Engineers*"]},
        {"major": "Animation", "introduction": "Gain valuable practical experience through live briefs, group work, placements and networking events and graduate ready to make your mark in the industry.", "assessment": {"exams": 0, "coursework": 100, "practical": 0}, "modules": ["Animation Foundations", "Character Animation", "Ideas, Design, Story", "Animation Studies", "Collaborative Projects", "The Animation Business", "Animation Studies 2", "Studio 1", "Animation Studies 3", "Studio 2", "Enterprise in Animation"]},
        {"major": "Architectural Technology and Design", "introduction": "Get valuable real-world advice from architecture professionals on this course, which is accredited by the Chartered Institute of Building (CIOB) (subject to conditions) and the Chartered Institute of Architectural Technologists (CIAT).", "assessment": {"exams": 19, "coursework": 79, "practical": 2}, "modules": ["Construction Technology and Services", "Design Studio 1", "Environmental Physics and Materials", "Commercial Development", "Design Representation", "Histories and Theories of Architecture", "Procurement and Contract Practice", "Technology and Design Studio 2", "Collaborative Practices in Building Information Management and Modelling - Technology and Design Studio 3"]},
        {"major": "Architecture", "introduction": "Develop your professional portfolio and lay the foundations for your career on this exciting course with full Royal Institute of British Architects (RIBA) validation and Architects Registration Board (ARB) accreditation.", "assessment": {"exams": 7, "coursework": 91, "practical": 2},  "modules": ["Design Studio 1", "Healthy and Responsible Architecture", "History of Architecture", "Low Carbon Structures", "Architectural Technology and Environment 2", "Architecture and Design Studio 2", "Design Representation", "Histories and Theories of Architecture", "Research and Design Strategies", "Advanced Technology and Environment 3", "Architecture and Design Studio 3", "Collaborative Practice", "Dissertation", "Theories of Architecture and Design", "Advanced Technology and Environment 3", "Architecture and Design Studio 3", "Collaborative Practice", "Dissertation", "Theories of Architecture and Design"]},
        {"major": "Architecture and Environmental Engineering", "introduction": "Become a designer of the future by learning the creative and analytical skills of both architects and engineers, and study towards professional status in both fields.", "assessment": {"exams": 19, "coursework": 77, "practical": 4},  "modules": ["Design Studio 1", "Engineering Principles (Building Engineering)", "Environmental Physics and Materials", "Mathematics for Civil and Environmental Engineering", "Building Services Applications", "Design Representation", "Histories and Theories of Architecture", "Research and Design Strategies", "Studio 2", "Applications of Mathematics in Civil and Environmental Engineering", "Design and Engineering Studio 3", "Interactive Systems and Comfort Control", "Low Carbon Building Services", "Theories of Architecture and Design", "Collaborative Practice", "Design and Engineering Studio 4", "Energy Management and Performance Evaluation", "Mechanical Services"]},
        {"major": "Architecture and Planning", "introduction": "This degree is unique because it's accredited by the Royal Institute of British Architects (RIBA), the Royal Town Planning Institute (RTPI), and the Architects Registration Board (ARB).", "assessment": {"exams": 6, "coursework": 92, "practical": 3}, "modules": ["Design Studio 1", "Healthy and Responsible Architecture", "Healthy Sustainable Communities", "History of Architecture", "Design Representation", "Future Places", "History of Architecture", "Research and Design Strategies", "Studio 2", "Collaborative Practice", "Design Studio 3", "Dissertation", "Planning Global Cities", "Planning Theory", "Agency Project A", "Design Studio 4", "Integrated Practice Studio", "Theories of Architecture and Design"]},
        {"major": "Audio and Music Technology", "introduction": "Develop advanced creative and technical skills and craft new technologies and practices on this leading course, accredited by Joint Audio Media Education Support (JAMES).", "assessment": {"exams": 0, "coursework": 0, "practical": 0}, "modules": ["Introductory Audio Programming", "Audio Engineering", "Audio Technology", "Music", "Audio Process Design and Implementation", "Audio Recording", "Music Technology Project", "Music Technology Project"]},
        {"major": "Automotive Engineering", "introduction": "Get your career off to a strong start with this IMechE accredited degree, by gaining experience through factory visits, professional briefings and testing your designs using our modern automotive simulator.", "assessment": {"exams": 0, "coursework": 0, "practical": 0}, "modules": ["Engineering Practice 1", "Solid Mechanics, Materials and Manufacturing", "Dynamics Modelling and Simulation", "Thermofluids", "Applied Electrical Technology", "Engineering Practice 2", "Engineering Research", "Structural Mechanics", "Applied Thermofluids", "Dynamics", "Systems Design", "Engineering Project", "Group Design and Integration Project", "Vehicle Design Fundamentals", "Automotive Manufacturing", "Emerging Automotive Technology 1", "Vehicle Dynamics", "Professionalism for Engineers (You will not study this module if you have completed the placement year)", "Engineering Project", "Group Design and Integration Project", "Vehicle Design Fundamentals", "Automotive Manufacturing", "Emerging Automotive Technology 1", "Vehicle Dynamics", "Professionalism for Engineers (You will not study this module if you have completed the placement year)"]} ,
        {"major": "Banking and Finance", "introduction": "We're one of the only Universities in the UK to offer direct access to real-time global financial data in our cutting-edge Bloomberg trading room.", "assessment": {"exams": 0, "coursework": 0, "practical": 0}, "modules": ["Financial Institutions and Markets", "Introduction to Finance", "Introductory Microeconomics", "Macroeconomics", "Statistics and Data Management", "Understanding Business and Financial Information (Accounting, Economics and Finance)", "Financial Accounting", "Governance and Ethics in Banking", "Introductory Econometrics", "Investment Banking", "Principles and Practice of Banking", "Final Year Project", "Contemporary Issues in Banking and Finance", "Work Integrated Learning or Cross Cultural Learning and Development", "Final Year Project", "Contemporary Issues in Banking and Finance", "Work Integrated Learning or Cross Cultural Learning and Development"]},
        {"major": "Biological Sciences", "introduction": "Explore human biology, ecology and molecular biology and tailor your degree to your own areas of interest.", "assessment": {"exams": 38, "coursework": 56, "practical": 7}, "modules": ["Life on Earth", "Human Anatomy and Physiology", "Cells Biochemistry and Genetics", "Skills for Biosciences", "Research Skills", "Research Dissertation Project"]},
        {"major": "Biomedical Science", "introduction": "This course gives you strong practical skills in the biomedical sciences, with the option to gain a year's experience with a leading employer in the UK or abroad.", "assessment": {"exams": 45, "coursework": 48, "practical": 8}, "modules": ["Biomedical Skills", "Infection and Disease", "Cells, Biochemistry and Genetics", "Human Anatomy and Physiology", "Molecular Cell Biology", "Applied Scientific Practice", "Studies in the Biology of Disease", "Research Dissertation Project", "Research Dissertation Project"]},
        {"major": "Building Services Engineering", "introduction": "Get valuable experience from world leaders in building services and learn how to create the next generation of smart, sustainable buildings.", "assessment": {"exams": 36, "coursework": 53, "practical": 6}, "modules": ["Mathematics for Civil and Environmental Engineering", "Engineering Principles (Building Engineering)", "Construction Technology and Services", "Law, Economics and Management", "Environmental Physics and Materials", "Building Services Applications", "Energy Transformations", "Applications of Mathematics in Civil and Environmental Engineering", "Procurement and Contract Practice", "Sustainability and Energy Simulations", "Interactive Systems and Comfort Controls", "Energy Management and Performance Evaluation", "Mechanical Services", "Design Project"]},
        {"major": "Building Surverying", "introduction": "Get your career off to the best possible start with accreditation from the Chartered Institute of Building (CIOB) (Subject to conditions), the Royal Institution of Chartered Surveyors (RICS) and the Chartered Association of Building Engineers (CABE).", "assessment": {"exams": 37, "coursework": 60, "practical": 3}, "modules": ["Law, Economics and Management", "Environmental Physics and Materials", "Construction Technology and Services", "Principles of Sustainable Design", "Management of Residential Refurbishment Projects", "Commercial Development", "Professional Practice for the Built Environment", "Professional Consultancy and Contract Administration", "Building Pathology", "Dissertation", "Sustainable Strategies for Property Management", "Commercial Refurbishment", "Conserving Buildings and Places", "Dissertation", "Sustainable Strategies for Property Management", "Commercial Refurbishment", "Conserving Buildings and Places"]},
        {"major": " Business (Team Entrepreneurship)", "introduction": "This is a groundbreaking course that shows you how to set up and run a business alongside your studies, giving you valuable entrepreneurial experience.", "assessment": {"exams": 0, "coursework": 72, "practical": 28}, "modules": ["Year one - routine and habits, building practices as individuals and teams, individual and team project experiments and reflecting", "Year two - develop practices as individuals and teams, develop projects and businesses, and specialisation as a team entrepreneur", "Final year - high performing individuals, growing ventures and businesses, high performing teams, and exit strategy from the course", "Running a Learning Organisation 1 (focuses on how to form your team)", "Managing My Learning and Development 1 (focuses on self-directed learning)", "Enterprising and Entrepreneurial Practice 1 (focuses on exploring venture creation)", "Enquiry into Enterprise and Entrepreneurship 1 (focuses on how to access expert knowledge)", "Running a Learning Organisation 2 (focuses on how to test team capabilities)", "Managing My Learning and Development 2 (teaches you more about self-leadership)", "Enterprising and Entrepreneurial Practice 2 (focuses on evaluating entrepreneurial opportunities)", "Enquiry into Enterprise and Entrepreneurship 2 (focuses on how to select your specialism)", "Running a Learning Organisation 3 (focuses on leveraging your team's performance)", "Managing My Learning and Development 3 (teaches you more about self-mastery)", "Enterprising and Entrepreneurial Practice 3 (focuses on refining entrepreneurial competencies)", "Enquiry into Enterprise and Entrepreneurship 3 (focuses on how to deliver thought leadership)"]} ,
        {"major": "Business and Events Management", "introduction": "Get involved in projects and activities with our partners Macmillan Cancer Care, Glastonbury Festival, and our Exhibition and Conference Centre.", "assessment": {"exams": 21, "coursework": 59, "practical": 20}, "modules": ["Introduction to Management", "Economics for Events and Marketing", "Understanding Business and Financial Information (Marketing, Events and Tourism)", "Understanding the Principles of Marketing (Marketing, Events and Tourism)", "Business Decision Making for Marketing and Events", "Enterprise and Entrepreneurship", "Events in Society", "Understanding Organisations and People (Marketing, Events and Tourism)", "Managing People", "Research Methods for Events and Marketing", "Planning and Managing Events", "Introductory Research Project (Marketing and Events)", "The Business of Events", "Practical Digital Skills or Management Skills (Marketing and Events)", "Introduction to Project Management or Financial Aspects for Marketing, Events and Tourism", "Specialised Events Practice", "Contemporary Issues in Events", "Strategic Management (Marketing, Events and Tourism)", "Staging and Evaluating Events", "Critical Business Enquiry Project or Enterprise Project or Applied Business Project or Business Project", "Specialised Events Practice", "Contemporary Issues in Events", "Strategic Management (Marketing, Events and Tourism)", "Staging and Evaluating Events", "Critical Business Enquiry Project or Enterprise Project or Applied Business Project or Business Project"]},
        {"major": "Business and Human Resource Management", "introduction": "Completing this course gets you an Intermediate Diploma in Human Resource Management from the CIPD. This tells future employers you have practical experience in the field.", "assessment": {"exams": 15, "coursework": 61, "practical": 24}, "modules": ["Introduction to Management", "Understanding Business and Financial Information (BIM)", "HRM and Leadership in Context", "Understanding Organisations and People (BIM)", "Understanding the Principles of Marketing (BIM)", "Contemporary Business Issues", "Business Decision Making for Management", "Enterprise and Entrepreneurship", "Managing People", "Management Skills (Business and Management)", "Accounting Information for Business (BIM)", "Contemporary Employment Relations", "Research Methods for Business", "Equality Law and Diversity Management", "Operations and Supply Management", "Research in Human Resource Management and Leadership", "Critical Business Enquiry project or Applied Business Project or Business Project", "Strategy and Human Resource Management", "Human Resource Development and Knowledge Management", "Managing Organisational Performance", "International Human Resource Management", "Prospects - careers in recruitment and HR"]},
        {"major": "Business and Management", "introduction": "This course is for those who want flexibility to design their own programme and the option to switch to specialised courses like Business Management with Marketing or Business and Human Resource Management after the first year.", "assessment": {"exams": 26, "coursework": 54, "practical": 20}, "modules": ["Introduction to Business and Management", "Enterprise and Entrepreneurship", "Understanding Business and Financial Information (Business, International and Management)", "Understanding the Business and Economic Environment", "Understanding Organisations and People (Business, International and Management)", "Understanding the Principles of Marketing (Business, International and Management)", "Contemporary Business Issues", "Business Decision Making for Management", "Managing People", "Management Skills (Business and Management)", "Accounting Information for Business (Business, International and Management)", "International Business", "Research Methods for Business", "Introductory Research Project", "Operations and Supply Management", "Strategic Management (Business, International and Management)", "Managing Organisational Change", "Integrated Business Management Simulation", "Strategic Management (Business, International and Management)", "Managing Organisational Change", "Integrated Business Management Simulation"]},
        {"major": "Business Computing", "introduction": "Develop an attractive mix of skills, a strong network and practical experience that will prepare you brilliantly for a career in computing, web, data analytics or marketing.", "assessment": {"exams": 27, "coursework": 58, "practical": 15}, "modules": ["IT Practice: Skills, Models and Methods", "Information Technology", "Business Applications", "Understanding Organisations and People (Marketing, Events and Tourism)", "Understanding Business and Financial Information (Business, International and Management)", "Data, Schemas and Applications", "IT Practice: Collaborative Project", "Foundation of Business Analytics", "Software Development Project or Information Systems Dissertation", "Business Intelligence and Data Mining", "Security Management in Practice", "Ethical and Professional Issues in Computing and Digital Media", "Sustainable Business and Computing", "Software Development Project or Information Systems Dissertation", "Business Intelligence and Data Mining", "Security Management in Practice", "Ethical and Professional Issues in Computing and Digital Media", "Sustainable Business and Computing"]},
        {"major": "Business Management andEconomics", "introduction": "After graduating, you'll be eligible for a placement with the Government Economic Service (GES), one of the biggest employers of economists in the UK. You could work for all sorts of government agencies around the world.", "assessment": {"exams": 40, "coursework": 55, "practical": 6}, "modules": ["Introduction to Management", "Economic Reasoning", "Understanding Business and Financial Information (Accounting, Economics and Finance)", "Introductory Microeconomics", "Introductory Macroeconomics", "Understanding Organisations and People (Accounting, Economics and Finance)", "Understanding the Principles of Marketing (Accounting, Economics and Finance)", "Statistics and Data Management", "Managing People", "Management and Cost Accounting", "Economic Theory, Policy and Applications", "Research Methods for Business", "Operations and Business Systems", "Good Business, Bad Business and Sustainability", "Strategic Management (Accounting, Economics and Finance)", "Applied Economics", "Managing Organisational Change (Accounting, Economics and Finance)", "Sustainable Business", "Work Integrated Learning or Cross Cultural Learning and Development or Placement Learning or Learning and Development on Study Year Abroad"]},
        {"major": "Business Management and Marketing", "introduction": "After graduating, you'll be eligible for a placement with the Government Economic Service (GES), one of the biggest employers of economists in the UK. You could work for all sorts of government agencies around the world.", "assessment": {"exams": 40, "coursework": 55, "practical": 5}, "modules": ["Introduction to Management", "Economic Reasoning", "Understanding Business and Financial Information (Accounting, Economics and Finance)", "Introductory Microeconomics", "Introductory Macroeconomics", "Understanding Organisations and People (Accounting, Economics and Finance)", "Understanding the Principles of Marketing (Accounting, Economics and Finance)", "Statistics and Data Management", "Managing People", "Management and Cost Accounting", "Economic Theory, Policy and Applications", "Research Methods for Business", "Operations and Business Systems", "Good Business, Bad Business and Sustainability", "Strategic Management (Accounting, Economics and Finance)", "Applied Economics", "Managing Organisational Change (Accounting, Economics and Finance)", "Sustainable Business", "Work Integrated Learning or Cross Cultural Learning and Development or Placement Learning or Learning and Development on Study Year Abroad"]},
        {"major": "Civil Engineering", "introduction": "Get industry ready on this accredited degree, which has high graduate employment rates and provides learning opportunities in the classroom, laboratory, and in the field. This degree is accredited by the Joint Board of Moderators (JBM).", "assessment": {"exams": 37, "coursework": 52, "practical": 11}, "modules": ["Civil Engineering Design and Technology", "Civil Engineering Field Skills and Surveying", "Construction Materials and Sustainability", "Engineering Practice 1", "Engineering Principles for Civil Engineering", "Computational Civil Engineering", "Engineering Practice 2", "Engineering Research", "Hydraulics and its Applications", "Integrated Structural Engineering", "Soil Mechanics", "Advanced Structural Analysis", "Engineering Project", "Geotechnics", "Infrastructure Design and Implementation Project", "Professionalism for Engineers*", "Transport Engineering Design", "Advanced Structural Analysis", "Engineering Project", "Geotechnics", "Infrastructure Design and Implementation Project", "Professionalism for Engineers*", "Transport Engineering Design"]},
        {"major": "Computer Science", "introduction": "Learn from experienced tutors who run our exceptional research in artificial intelligence (AI). Build intelligent algorithms and computer systems and explore the evolving world of Smart Devices. Study one of three specialist pathways, focusing on AI or Smart Devices, or Computer Science as a whole.", "assessment": {"exams": 37, "coursework": 58, "practical": 5}, "modules": ["Artificial Intelligence 1", "Computer Systems Architecture", "Foundations of Computing", "Principles of Programming", "Web Development and Databases", "Advanced Algorithms", "Operating Systems", "Systems Development Group Project", "Digital Systems Project", "Distributed and Enterprise Software Development", "Digital Systems Project", "Distributed and Enterprise Software Development"]},
        {"major": "Construction Project Management", "introduction": "Work either full or part-time towards Chartered Builder or Chartered Construction Manager status and develop valuable industry skills on collaborative projects.", "assessment": {"exams": 31, "coursework": 64, "practical": 5}, "modules": ["Law, Economics and Management", "Construction Technology and Services", "Environmental Physics and Materials", "Principles of Sustainable Design", "Construction Technology and Building Services", "Project Management Tools and Techniques", "Procurement and Contract Practice", "Site Management", "Professional Practice for the Built Environment", "People and Financial Management", "Technological Innovation and Life Cycles", "Strategic and Operational Management", "Collaborative Practice", "Dissertation", "People and Financial Management", "Technological Innovation and Life Cycles", "Strategic and Operational Management", "Collaborative Practice", "Dissertation"]},
        {"major": "Creative and Professional Writing", "introduction": "Study fiction, non-fiction, script and corporate copywriting, and shape your degree in line with your creative ambitions.", "assessment": {"exams": 6, "coursework": 83, "practical": 11}, "modules": ["Creative Practice and Writing Mechanics", "Fundamentals of Writing: Fiction", "Fundamentals of Writing: Non-fiction and Copy", "Fundamentals of Writing: Script", "Reading for Writing: Developing a Novel", "Writing for Screen", "Writing for Stage", "A Career in Fiction", "Creative Project", "Creative Writing and the Self", "Publishing: From Commission to Print (compulsory if you choose the Publishing pathway)", "The Professional Copywriter (compulsory if you choose the Copywriting pathway)", "The Working Scriptwriter (compulsory if you choose the Scriptwriting pathway)", "A Career in Fiction", "Creative Project", "Creative Writing and the Self", "Publishing: From Commission to Print (compulsory if you choose the Publishing pathway)", "The Professional Copywriter (compulsory if you choose the Copywriting pathway)", "The Working Scriptwriter (compulsory if you choose the Scriptwriting pathway)"]} ,
        {"major": "Creative Music Technology", "introduction": "Develop and refine your creative process using inspiration from past and present composers. Express and apply this in different areas using a broad range of techniques and technologies. Recognised as the 'most musical city' in the UK (per capita), it is a fantastic place to study all genres of music.", "assessment": {"exams": 21, "coursework": 62, "practical": 17}, "modules": ["Introductory Audio Programming", "Audio Technology", "Audio Engineering", "Music", "Advanced Composition", "Music Technology Project", "Music Portfolio", "Music Technology Project", "Music Portfolio"]},
        {"major": "Criminology", "introduction": "Explore crime from multiple angles, and arm yourself with the specialist knowledge and skills that will get you noticed by employers when you graduate.", "assessment": {"exams": 37, "coursework": 57, "practical": 6}, "modules": ["Introduction to Criminological Theory", "Introduction to Criminal Justice", "Understanding Crime", "Critical Thinking", "Social Issues and Social Problems", "Researching Crime and Society", "Contemporary Perspectives in Criminology", "Criminology in Action: Engaging in the Real World", "Nature and Use of Research", "Transnational Crime and Comparative Criminology", "Criminology Partnership Project or Criminology Project", "Transnational Crime and Comparative Criminology", "Criminology Partnership Project or Criminology Project"]},
        {"major": "Criminology and Sociology", "introduction": "You'll work with organisations through placements and internships, and get to develop your own insights and ideas to help improve people's lives.", "assessment": {"exams": 34, "coursework": 56, "practical": 10}, "modules": ["Foundations in Social Theory", "Introduction to Criminological Theory", "Critical Thinking (Sociology and Criminology)", "Sociological Practice - Becoming a Social Scientist", "Introduction to Criminal Justice", "Understanding Crime", "Theorising Social Life", "Nature and Use of Research (Sociology) or Nature and Use of Research (Criminology)", "Developing Self and Society (Sociology) or Criminology in Action: Engaging in the Real World", "Contemporary Perspectives in Criminology", "Sociology Project and Placement Module or Criminology Project or Criminology Partnership Project", "Transnational Crime and Comparative Criminology", "Sociology Project and Placement Module or Criminology Project or Criminology Partnership Project", "Transnational Crime and Comparative Criminology"]},
        {"major": "Criminology and Psychology", "introduction": "Study both subjects equally in your first year and then choose which you want to major in. Whichever direction you take, this dual degree will give you a strong grounding for lots of interesting careers.", "assessment": {"exams": 41, "coursework": 51, "practical": 9}, "modules": ["Introduction to Criminal Justice", "Introduction to Criminological Theory", "Introduction to Psychology", "Research Design and Analysis 1", "Understanding Crime", "Contemporary Perspectives in Criminology", "Criminology in Action: Engaging in the Real World", "Nature and Use of Research (Criminology)", "Transnational Crime and Comparative Criminology", "Criminology Partnership Project or Criminology Project", "Transnational Crime and Comparative Criminology", "Criminology Partnership Project or Criminology Project"]},
        {"major": "Cyber Security and Digital Forensics", "introduction": "Play an important role helping organisations manage cyber-attacks and investigate digital evidence.", "assessment": {"exams": 25, "coursework": 55, "practical": 19}, "modules": ["Programming in C++", "Computer and Network Systems", "Introduction to Databases", "Computer Crime and Digital Evidence", "Operating Systems", "Data Science for Cyber Security", "Security and Forensic Tools", "Secure Computer Networks", "Security Management in Practice", "Cyber Security Project", "Global Landscapes of Cyber Security and Adversaries", "Forensic Computing Practice", "Security Management in Practice", "Cyber Security Project", "Global Landscapes of Cyber Security and Adversaries", "Forensic Computing Practice"]},
        {"major": "Diagnostic Radiography", "introduction": "Develop specialist diagnostic radiography knowledge and skills. You'll have access to industry-standard technology and undertake work placements in NHS and private healthcare settings.", "assessment": {"exams": 28, "coursework": 47, "practical": 25}, "modules": ["Physical Sciences and Imaging Technology 1", "Fundamentals of Human Anatomy and Physiology", "Diagnostic Radiography Professional Practice 1", "Clinical Context and Applications of Diagnostic Radiography 1", "Principles of Radiographic Imaging Technique", "Professional Behaviour and Health Psychology", "Informing Practice through Research and Inquiry", "Clinical Context and Applications of Diagnostic Radiography 2", "Physical Sciences and Imaging Technology 2", "Diagnostic Radiography Professional Practice 2", "Healthy Futures", "Research and Evidence in Practice", "Continuous Professional Development and Employability Skills", "Skills for Informing Practice", "Diagnostic Radiography Professional Practice 3"]},
        {"major": "Digital Media", "introduction": "Build your professional portfolio by applying your problem-solving skills and technical knowledge to real-world projects.", "assessment": {"exams": 0, "coursework": 89, "practical": 11}, "modules": ["Graphic and Web Design Studio", "Introduction to Creative Coding", "Media Studio", "Principles of 3D Environments", "Creative and Physical Computing", "Media Production", "User Experience", "Comprehensive Creative Technologies Project or Creative Technologies Project", "Design Enterprise Studio", "Comprehensive Creative Technologies Project or Creative Technologies Project", "Design Enterprise Studio"]},
        {"major": "Drama and Acting", "introduction": "Learn acting techniques for stage and screen alongside writing and theatre history to graduate confident, creative and ready for an exciting future in the industry.", "assessment": {"exams": 0, "coursework": 39, "practical": 61}, "modules": ["Introduction to Actor Training", "Introduction to Physical Theatre", "Introduction to Creative Writing", "Introduction to Performance Texts and Contexts", "Acting for Stage", "Devising Physical Theatre", "Final Year Project", "Acting for Screen"]},
        {"major": "Early Childhood", "introduction": "This course provides an excellent foundation for careers with children, or for further study. It offers a deep dive into various aspects of childhood and child development, focusing on rights, health, and educational practices.", "assessment": {"exams": 0, "coursework": 70, "practical": 30}, "modules": ["Constructions of Childhood", "Exploring Play", "Children's Rights, Well-Being and Health", "Working with all Children", "Guided Studies", "Becoming a Researcher", "Children's Meaning Making", "Early Childhood Policy and Comparative Curricula", "Leadership and Professional Futures", "Reflective Practice", "Dissertation or Guided Study (45 credits)", "Debating Childhoods", "Emerging Languages and Identities", "The Development of Reasoning", "Guided Studies (15 or 30 credits)"]} ,
        {"major": "Economics", "introduction": "We have a strong track record of securing placements with public sector employers like the Treasury, Home Office, and Office of National Statistics; with financial institutions such as Lloyds Bank; and in businesses, charities, and international organisations.", "assessment": {"exams": 51, "coursework": 40, "practical": 9}, "modules": ["Microeconomics", "Macroeconomics", "Evolutions of Economy and Industry", "Statistics and Data Management", "Model Building in Economics I", "History of Economic Thought", "Applied Microeconomics", "Macroeconomics: Theory and Applications", "Economic Research Methods", "Introductory Econometrics", "Model Building in Economics II", "Project", "Economic Theory and Policy", "Work Integrated Learning or Cross Cultural Learning and Development or Placement Learning or Learning and Development on Study Year Abroad", "Project", "Economic Theory and Policy", "Work Integrated Learning or Cross Cultural Learning and Development or Placement Learning or Learning and Development on Study Year Abroad"]},
        {"major": "Education", "introduction": "Make yourself highly employable on this future-facing degree, which is informed by principles of sustainability and can be adapted to your interests. Develop specialist knowledge and skills in the areas of Special Educational Needs and Disabilities (SEND) and Digital Learning.", "assessment": {"exams": 0, "coursework": 70, "practical": 30}, "modules": ["Becoming an educator", "Education, society and inclusivity", "Educational journeys", "Digital learning", "Researching education", "Education in practice, including a focus on additional needs and digital learning", "Professional skills", "Inclusion", "Debates in education", "Education project", "International comparative education", "Your professional futures", "Debates in education", "Education project", "International comparative education", "Your professional futures"]},
        {"major": "Electrical and Electronic Engineering", "introduction": "Study full or part-time on this course designed to equip you with the skills to succeed in your career. The program offers a blend of theoretical knowledge and practical application, making it ideal for students aiming to excel in the dynamic fields of electronics and robotics.", "assessment": {"exams": 32, "coursework": 57, "practical": 10}, "modules": ["Engineering Practice 1", "Principles of Electrical Engineering", "Mathematical Modelling for Electronics and Robotics", "Programming for Engineers", "Applied Electronics", "Engineering Practice 2", "Electrical Machines and Power Systems", "Embedded Systems", "Engineering Research", "Signals and Systems", "Analogue Electronic Systems", "Engineering Project", "Group Design and Integration Project", "Control Systems Design", "Power Electronics and Energy Systems", "Professionalism for Engineers", "Engineering Project", "Group Design and Integration Project", "Control Systems Design", "Power Electronics and Energy Systems", "Professionalism for Engineers"]},
        {"major": "English Language and Linguistics", "introduction": "Study towards one of the top degrees of its type in the UK, exploring the complexity of language and how it relates to wider society, culture and the mind. This program delves into various aspects of language, offering insights into its structural, social, and cognitive dimensions.", "assessment": {"exams": 44, "coursework": 51, "practical": 6}, "modules": ["Constructing Language(s)", "Phonetics and Forensic Linguistics", "Making Meaning", "English: Past, Present and Future", "Studying Speech Communities", "Language Acquisition", "Teaching English to Speakers of Other Languages", "Creative Writing and the Self", "Critical Discourse Analysis", "Language in the Mind", "The Cultural History of the English Language", "Language Project", "Gender, (Im)politeness and Power in Language", "Language and Cognition", "Teaching English to Speakers of Other Languages", "Creative Writing and the Self", "Critical Discourse Analysis", "Language in the Mind", "The Cultural History of the English Language", "Language Project", "Gender, (Im)politeness and Power in Language", "Language and Cognition"]},
        {"major": "English Literature", "introduction": "On this course, you will read an exciting range of literary texts, gain excellent knowledge of literature as a public good, and develop high-level skills for your career. This program explores various dimensions of literature, from its role in society to its impact on global cultures.", "assessment": {"exams": 20, "coursework": 69, "practical": 11}, "modules": ["Literature and Ideas", "Literature and the Marketplace", "Close Reading", "The Child in Literature", "Imagined Worlds: Utopian and Dystopian Literature", "Travel, Writing and Colonization", "Literature in the World", "English Independent Project"]},
        {"major": "English Literature with Writing", "introduction": "On this course, you will pursue creative and professional writing alongside a rigorous academic curriculum in English literature. There is a dedicated writing module every year and a placement module in year three, equipping students with both the creative and critical expertise needed for a variety of careers.", "assessment": {"exams": 18, "coursework": 70, "practical": 12}, "modules": ["Literature and Ideas", "Genre and Creative Writing", "Close Reading", "The Child in Literature", "Imagined Worlds: Utopian and Dystopian Literature", "Travel, Writing and Colonization", "Occasions for Writing", "English Independent Project", "Writing in Practice"]},
        {"major": "Environmental Management", "introduction": "Make a difference in the world. Learn about environmental systems, the human impacts on them and how to manage those interactions sustainably - and gain a strong grounding for an environmentally-focused career.", "assessment": {"exams": 3, "coursework": 58, "practical": 37}, "modules": ["Environmental Systems and Ecosystems", "Climate Change and Mitigation", "Sustainability and Resource Management", "Environmental Policy and Regulation", "Fieldwork and Research Methods", "Environmental Impact Assessment", "Ecology and Conservation", "Environmental Management", "Dissertation"]},
        {"major": "Environmental Science", "introduction": "Accredited by the Institution of Environmental Sciences (IES), this course prepares you for a career tackling some of today's most important environmental challenges.", "assessment": {"exams": 32, "coursework": 56, "practical": 12}, "modules": ["Life on Earth", "The Earth", "Field Skills (includes residential field trip, where possible)", "Environment and Society.", "Environmental and Field Techniques (includes residential field trip, where possible)", "Ecology and Ecosystem Protection.", "Dissertation Project or Independent Research Project", "Resource Security and Sustainability.", "Dissertation Project or Independent Research Project", "Resource Security and Sustainability."]},
        {"major": "Fashion Communication", "introduction": "BA(Hons) Fashion Communication was developed alongside industry experts and has produced Graduate Fashion Week award-winners across several categories. This interdisciplinary, practice-led course enables you to explore how we communicate fashion through different creative media.", "assessment": {"exams": 0, "coursework": 100, "practical": 0}, "modules": ["Visual Culture 1", "Exploring Practice in Fashion Communication", "Introduction to Fashion Communication", "Introduction to Professional Practice: Observation and Exploration.", "Professional Practice: Work Experience, Seeking, Doing, Reflecting", "Contextualising Practice in Fashion Communication", "Visual Culture 3", "Graduate Strategies: Reflecting, Consolidating and Planning for Exit", "Self-Directed Study in Fashion Communication."]},
        {"major": "Fashion Textiles", "introduction": "Learn to create garments, accessories and textile collections for fashion and interiors through sustainably driven and digitally enabled design.", "assessment": {"exams": 0, "coursework": 100, "practical": 0}, "modules": ["Introduction to Fashion Textiles", "Exploring Practice in Fashion Textiles", "Professional Practice and Work Experience in Fashion Textiles 1", "Visual Culture 1.", "Creative Analysis", "Developing Practice in Fashion Textiles 1", "Developing Practice in Fashion Textiles 2.", "Preparation for Extended Study in Fashion Textiles (you'll choose either the 15 or 30 credit version).", "Visual Culture 3 (you'll choose either the 15 or 30 credit version)", "Extended Study in Fashion Textiles (you'll choose either the 30 or 45 credit version).", "Preparation for Extended Study in Fashion Textiles (you'll choose either the 15 or 30 credit version).", "Visual Culture 3 (you'll choose either the 15 or 30 credit version)", "Extended Study in Fashion Textiles (you'll choose either the 30 or 45 credit version)."]},
        {"major": "Film Studies", "introduction": "Gain practical experience, make valuable contacts and build the skills you need for an exciting career in the thriving film and television industry.", "assessment": {"exams": 12, "coursework": 84, "practical": 5}, "modules": ["Film Style and Meaning", "The Movie Experience: Audience, Culture and Taste", "Hollywood and Beyond: Commerce, Creativity and Authorship", "Imagining Realities", "Spectacle, Action, Narrative.", "Hollywood and World Cinema", "British Film and Television", "Adaptation: Screenwriting and Narrative Form", "Screen Representations: Difference and Diversity", "Film Genre", "Professional Writing About Film.", "Film Studies Independent Project.", "Film Studies Independent Project."]},
        {"major": "Filmmaking", "introduction": "This production-based course gives you the practical and intellectual skills you need for a successful career in today's creative industries.", "assessment": {"exams": 0, "coursework": 97, "practical": 3}, "modules": ["Film Style 1: Sound and Vision", "Introduction to Filmmaking", "Professional Practice: Short Form 1", "Script and the Actor.", "Film Style 2", "Professional Practice 2", "Story 2: Documentary", "Story 2: Narrative.", "Independent Research Project in Filmmaking", "Production 1", "Production 2", "Professional Practice 3", "Short Form 3: Commercials."]},
        {"major": "Fine Art", "introduction": "Build your confidence in fine art practice and develop a range of transferable professional skills to support your future in the creative industries and beyond.", "assessment": {"exams": 0, "coursework": 100, "practical": 0}, "modules": ["Introduction to Fine Art", "Exploring Practice in Fine Art", "Visual Culture 1", "Introduction to Professional Practice.", "Creative Analysis", "Developing Practice in Fine Art.", "Extended Study in Fine Art", "Professional Practice: Graduate Strategies."]},
        {"major": "Forensic Science", "introduction": "Accredited by The Chartered Society of Forensic Sciences, this course gives you a compelling mix of academic knowledge, practical experience and advanced skills to fast-track your career.", "assessment": {"exams": 42, "coursework": 50, "practical": 9}, "modules": ["Chemistry in Context", "Human Biological Systems", "Scientific Investigation of Crime", "Scientific Skills.", "Forensic Analysis", "Law and Expert Evidence", "Drugs and Toxicology.", "Forensic Project.", "Forensic Project."]},
        {"major": "Games Technology", "introduction": "Use engines like Unity and UnrealEngine to develop games for various platforms and gain first-hand industry experience on live projects through our in-house studio, PlayWest.", "assessment": {"exams": 10, "coursework": 83, "practical": 7}, "modules": ["Game Development Evolution", "Games in C++", "Games Technology: 101", "Principles of 3D Environments.", "Game Engine Programming", "Gameplay Programming", "More Games in C++", "Play and Games.", "Advanced Technologies", "Commercial Games Development*", "Comprehensive Creative Technologies Project.", "Advanced Technologies", "Commercial Games Development*", "Comprehensive Creative Technologies Project."]},
        {"major": "Geography", "introduction": "This course is accredited by the Royal Geographical Society (with IBG). Take a sandwich year and study with one of our international partners in locations such as the US or Canada.", "assessment": {"exams": 39, "coursework": 41, "practical": 20}, "modules": ["An Introduction to Geographic Information Systems and Remote Sensing", "Environmental Challenges", "Field Study in Human Geography", "Geographies of Globalisation", "People, Places and Change.", "Applied Geographic Information Systems (GIS)", "Professional Development", "Researching Human Geography.", "Extended Independent Project."]},
        {"major": "Graphic Design", "introduction": "Study in a studio environment with professional-standard facilities and the focus on the real-world skills you need to succeed in your career.", "assessment": {"exams": 0, "coursework": 100, "practical": 0}, "modules": ["Introduction to Words and Images", "Communicating with Words and Images", "Visual Culture 1", "Professional Practice and Work Experience 1.", "Exploring Graphic Design Process", "Visual Culture 2.", "Preparation for Extended Study in Graphic Design or *Introduction to Level 3 Graphic Design", "Extended Study in Graphic Design", "Visual Culture 3", "Professional Practice and Work Experience 3."]},
        {"major": "History", "introduction": "Study the history of Britain, Europe, America, Asia and Africa and develop valuable skills and a sense of enquiry that you can apply to both the past and the present.", "assessment": {"exams": 33, "coursework": 64, "practical": 3}, "modules": ["A Global History of Europe", "Early Modern British History: Reformation to the Rebellion", "Europe and the World Order 1914-1945", "Europe in the Age of Enlightenment and Revolution", "History and Evidence", "Modern British History", "The Global Cold War, 1945-1989", "Working with History.", "History in Practice", "Making History", "Applied Historical Research.", "Applied Historical Research."]},
        {"major": "Illustration", "introduction": "Learn in a creative and supportive studio environment with professional-standard facilities and a focus on helping you gain real-world skills for the workplace.", "assessment": {"exams": 0, "coursework": 100, "practical": 0}, "modules": ["Introduction to Illustration", "Narrative and Sequence", "Professional Practice and Work Experience in Illustration 1", "Visual Culture 1", "Visual Essay.", "Word and Image", "Process and Practice", "Professional Practice and Work Experience in Illustration 2", "Visual Culture 2", "Developing Visual Narratives.", "Preparation for Extended Study in Illustration", "Extended Study in Illustration", "Professional Practice and Work Experience in Illustration 3", "Visual Culture 3."]},
        {"major": "Integrated Wildlife Conservation", "introduction": "We're the only university to offer a FdSc Integrated Wildlife Conservation foundation degree in partnership with a working zoo, learning from conservation scientists with real-world experience.", "assessment": {"exams": 25, "coursework": 58, "practical": 17}, "modules": ["Ecology and Environmental Systems", "Wildlife Biology", "Wildlife and People", "Professional Work Skills.", "Conservation Biology", "Animal Behaviour for Wildlife Conservation", "Effective Communication for Conservation", "Integrating Sustainable Development and Conservation", "Work and Research Skills."]},
        {"major": "Interior Architecture", "introduction": "This course is inspired and informed by our partnerships with industry and academia, giving you a degree that sets you up to succeed in your career.", "assessment": {"exams": 6, "coursework": 90, "practical": 4}, "modules": ["Design Studio 1", "Healthy and Responsible Architecture", "History of Architecture", "Objects and Experiences.", "Aesthetics and Product Language", "Design Representation", "Histories and Theories of Architecture", "Interior Architecture Design Studio 2", "Product CAD", "Research and Design Strategies.", "Collaborative Practice", "Conserving Buildings and Places", "Dissertation", "Interior Architecture Design Studio 3", "Theories of Architecture and Design.", "Collaborative Practice", "Conserving Buildings and Places", "Dissertation", "Interior Architecture Design Studio 3", "Theories of Architecture and Design."]},
        {"major": "Interior Design", "introduction": "Build an impressive portfolio, real-world experience, project management skills and the technical expertise needed for a successful career in interior design.", "assessment": {"exams": 0, "coursework": 100, "practical": 0}, "modules": ["Introduction to Interior Design", "Exploring Practice in Interior Design", "Professional Practice and Work Experience in Interior Design", "Visual Culture 1.", "Developing Practice in Interior Design", "Visual Culture 2.", "Preparation for Extended Study in Interior Design", "Extended Study in Interior Design", "Professional Practice and Work Experience in Interior Design 3", "Visual Culture 3."]},
        {"major": "International Business", "introduction": "You'll spend your third year studying or working at one of our many partner institutions overseas; these include organisations in Berlin, Stockholm, Paris, Barcelona, Malaysia and Amsterdam, or alternatively working at a multinational company in the UK or internationally.", "assessment": {"exams": 27, "coursework": 53, "practical": 20}, "modules": ["Introduction to Management", "Understanding Business and Financial Information (Business, International and Management (BIM))", "Understanding the Principles of Marketing (BIM)", "Business Decision Making for Management", "Contemporary Business Issues", "Understanding Organisations and People (BIM)", "Enterprise and Entrepreneurship", "International Business Context.", "Global Managing People (including study year abroad preparation)", "Theory and Practice of International Business", "Research Methods for Business", "Global Management Skills", "Operations and Supply Management", "Accounting Information for Business", "Introductory Research Project", "Intercultural Communications.", "Managing Organisational Change", "Integrated Business Management Simulation", "Strategic Management (BIM)", "Multinationals in the Domestic and Global Context."]},
        {"major": "International Business Management", "introduction": "This course is available to international direct entry students at UWE Bristol and at selected overseas partners.", "assessment": {"exams": 22, "coursework": 70, "practical": 8}, "modules": ["Meeting the Management Challenge (Business, International and Management)", "Understanding Business and Financial Information (Business, International and Management)", "Understanding Organisations and People (Business, International and Management)", "Engaging in Critical Business Enquiry (Business, International and Management)", "Understanding the Business and Economic Environment (Business, International and Management)", "Understanding the Principles of Marketing (Business, International and Management).", "Managing People (Business, International and Management)", "Managing Business Processes (Business, International and Management)", "International Business", "Methods of Enquiry (Business, International and Management)", "Accounting Information for Business (Business, International and Management)", "One optional module from the list below:", "Managing Organisational and Individual Change (Business, International and Management)", "Strategic Management (Business, International and Management)", "Multinationals in the Domestic and Global Context", "Business Project, Critical Business Enquiry Project or Applied Business Project*", "One optional module from the list below:"]},
        {"major": "Law", "introduction": "Stand out to employers by gaining professional experience through our Business and Law Clinic and developing your practical skills through creative assessment and real-world projects.", "assessment": {"exams": 61, "coursework": 35, "practical": 4}, "modules": ["Contract Law", "Criminal Law", "Law of Torts", "Public Law.", "Equity and Trusts", "Land Law.", "Advocacy", "Company Law in Context", "Criminal Justice", "Dissertation", "Equality and the Law", "European Union Law in Context**", "Family Law", "Intellectual Property", "International Business Law", "International Human Rights Law", "Law in Action*", "Law of Financial Crime", "Lawyering in Practice*", "Media and Entertainment", "Medical Law", "Preparing for Court", "Real Estate Law and Practice", "Student Lawyer Module*", "Terrorism and Counter-terrorism: Law, Society and Policy.", "Bristol Law Centre", "Watkins Solicitors", "Red Cross", "Death Row", "Citizens Advice", "Local schools."]},
        {"major": "Law and Criminology", "introduction": "Get access to advanced computing systems, laboratories, mock courtrooms and simulations that give you real-world experience to succeed in your career.", "assessment": {"exams": 46, "coursework": 45, "practical": 9}, "modules": ["Criminal Law", "Foundations for Law.", "Criminology in Action: Engaging with the Real World", "Nature and Use of Research (Criminology).", "Transnational Crime and Comparative Criminology", "Law Project*", "Transnational Crime and Comparative Criminology", "Law Project*"]},
        {"major": "Marketing ", "introduction": "This course is accredited by the Chartered Institute of Marketing (CIM), giving you valuable exemptions from professional exams, access to the CIM network and extra value for your CV.", "assessment": {"exams": 18, "coursework": 61, "practical": 21}, "modules": ["Introduction to Management", "Economics for Events and Marketing", "Understanding Business and Financial Information (Marketing, Events and Tourism)", "Understanding the Principles of Marketing for Marketing and Events", "Business Decision Making for Marketing and Events", "Enterprise and Entrepreneurship", "Marketing in Society", "Understanding Organisations and People (Marketing, Events and Tourism).", "Consumer Behaviour", "Research Methods for Events and Marketing", "Applied Marketing Practice", "Introductory Research Project (Marketing and Events)", "Service Operations", "Integrated Marketing Communications.", "Practical Digital Skills or Management Skills (Marketing and Events)", "Introduction to Digital Strategy or Financial Aspects for Marketing, Events and Tourism.", "Specialised Marketing Practice", "Contemporary Issues in Marketing", "Brand Management."]},
        {"major": "Mathematics", "introduction": "Accredited by the Institute of Mathematics and its Applications (IMA), this course will enable you to become proficient in advanced mathematical and statistical concepts, and to explore their real-world applications.", "assessment": {"exams": 67, "coursework": 33, "practical": 0}, "modules": ["Calculus and Numerical Techniques", "Mathematical Structures", "Statistical Investigations", "The Professional Mathematical Scientist 1.", "Calculus and Numerical Analysis", "Graphs, Algebra and Algorithms", "Statistical Applications", "Professional Mathematical Scientist 2.", "Applications of Computational Mathematics", "Mathematical Sciences Project or Mathematics Education Project.", "Applications of Computational Mathematics", "Mathematical Sciences Project or Mathematics Education Project."]},
        {"major": "Mechanical Engineering", "introduction": "Get industry ready with this IMechE accredited degree that consistently achieves high graduate employment rates and can be studied on a day release basis.", "assessment": {"exams": 57, "coursework": 40, "practical": 3}, "modules": ["Engineering Practice 1", "Solid Mechanics, Materials and Manufacturing", "Dynamics Modelling and Simulation", "Thermofluids", "Applied Electrical Technology.", "Engineering Practice 2", "Engineering Research", "Structural Mechanics", "Applied Thermofluids", "Dynamics", "Systems Design.", "Professionalism for Engineers*", "Engineering Project", "Group Design and Integration Project.", "Professionalism for Engineers*", "Engineering Project", "Group Design and Integration Project."]},
        {"major": "Mechatronics Engineering", "introduction": "Gain industry-like experience in our Digital Engineering Laboratory by working on Cyber-Physical Factory, Virtual and Augmented Reality Space and Artificial Intelligence based experiments. Our facilities are equipped with modules from SIEMENS, FESTO, and other leading industrial equipment providers.", "assessment": {"exams": 0, "coursework": 71, "practical": 29}, "modules": ["Engineering Practice 1", "Mathematical Modelling for Electronics and Robotics", "Applied Electronics", "Programming for Engineers", "Fundamental Mechatronics Principles.", "Engineering Practice 2", "Engineering Research", "Microcontroller Applications Group Lab", "Industrial Data Analytics", "Digital Manufacturing and Industry", "Industrial Internet of Things.", "Engineering Project", "Group Design and Integration Project", "Professionalism for Engineers", "Applied Artificial Intelligence", "Biomechatronics.", "Masters Group Capstone Project", "Advanced Mechatronics", "Modern Control for Mechatronics.", "Smart Factory Modelling and Simulation", "Industrial Systems Validation", "Digital Signal Processing", "Industrial Applications of Vision and Automation", "Power Electronics", "Electromechanical Systems Integration."]},
        {"major": "Media Communications", "introduction": "This course equips you with a deep understanding of media culture so you can communicate effectively between media makers, organisations, their clients and end users.", "assessment": {"exams": 10, "coursework": 83, "practical": 7}, "modules": ["Contemporary Digital Practice", "Network Culture", "Communications Contexts", "Communicating for Change.", "Researching Media Cultures", "Communication Practice", "Engaging Audiences.", "Major Research Project", "Live Brief", "Work Experience"]},
        {"major": "Media Production", "introduction": "Develop strong production and research skills, hone in on your particular areas of interest, and carve out a niche as a digital creative media professional in a fast-paced sector.", "assessment": {"exams": 1, "coursework": 81, "practical": 18}, "modules": ["Introduction to Contemporary Digital Media", "Media Networks", "Audio and Storytelling", "Writing for Production.", "Practical Research Methods.", "Professional Practice in Media or Professional Development on Placement* - Media Production Project or Dissertation."]},
        {"major": "Midwifery", "introduction": "Our employer links, practical focus and the clinical experience offered means that 95% of our graduates are in work or further study six months after graduation.", "assessment": {"exams": 10, "coursework": 50, "practical": 40}, "modules": ["The Context of Midwifery Practice 1", "The Context of Midwifery Practice 2", "Holistic Midwifery Practice 1", "Holistic Midwifery Practice 2", "The Midwife as a Skilled Practitioner 1.", "The Context of Midwifery Practice 3", "The Context of Midwifery Practice 4", "Holistic Midwifery Practice 3", "Holistic Midwifery Practice 4", "The Midwife as a Skilled Practitioner 2.", "Holistic Midwifery Practice 5", "Holistic Midwifery Practice 6", "Promoting Excellence for Midwifery Practice", "The Midwife as a Skilled Practitioner 3."]},
        {"major": "Nursing (Adult)", "introduction": "Our employer links, practical focus and the clinical experience offered means that you'll develop the confidence and critical skills you need to propel your adult nursing career.", "assessment": {"exams": 33, "coursework": 33, "practical": 34}, "modules": ["Anatomy, Physiology and Pharmacology for Nursing", "Episodes of Care 1", "Fundamentals of Nursing Practice", "Principles of Nursing (Field Specific)", "Sustainable Global Public Health", "Assessment and Decision Making", "Episodes of Care 2", "Episodes of Care 3", "Pharmacology and Medicines Management", "Research Methodologies of Nursing Enquiry", "Supporting People with Complex Needs", "Episodes of Care 4", "Leadership and Supervision", "Nursing Final Project", "Transition to Registration"]},
        {"major": "Nursing (Children and Young People)", "introduction": "Our employer links, practical focus and the clinical experience offered means that you'll develop the confidence and critical skills you need to propel your children's and young people nursing career.", "assessment": {"exams": 33, "coursework": 33, "practical": 34}, "modules": ["Anatomy, Physiology and Pharmacology for Nursing", "Episodes of Care 1", "Fundamentals of Nursing Practice", "Principles of Nursing (Field Specific)", "Sustainable Global Public Health", "Assessment and Decision Making", "Episodes of Care 2", "Episodes of Care 3", "Pharmacology and Medicines Management", "Research Methodologies of Nursing Enquiry", "Supporting People with Complex Needs", "Episodes of Care 4", "Leadership and Supervision", "Nursing Final Project", "Transition to Registration"]},
        {"major": "Occupational Therapy", "introduction": "The strong practical focus, our close links with employers, and the experience of our academic team, mean that a high percentage of graduates are in work or further study after six months.", "assessment": {"exams": 24, "coursework": 38, "practical": 38}, "modules": ["Human Occupation, Health and Well-being: Part 1", "Human Occupation, Health and Well-being: Part 2", "Fundamentals of Human Anatomy and Physiology (Occupational Therapy)", "Aspects of Human Performance", "Foundations of Professional Practice for Occupational Therapy 1", "Occupational Therapy and Physical Challenges", "Occupational Therapy and Psychosocial Challenges", "Professional Practice for Occupational Therapy 2", "Occupational Therapy and Complex Needs", "Informing Practice Through Research and Inquiry (Occupational Therapy)", "Occupational Therapy Skills and Strategies for Practice", "Professional Practice for Occupational Therapy 3", "Professional Reflexivity in Practice", "Research and Evidence in Practice (Occupational Therapy)", "Promoting Occupation and Leadership in Evolving Practice", "Leadership Skills in Context"]},
        {"major": "Paramedic Science", "introduction": "This course was jointly developed with the South Western Ambulance Service NHS Trust (SWAST). It's also approved by the Health and Care Professions Council (HCPC), so you will be eligible to apply for registration to work as a paramedic once you graduate.", "assessment": {"exams": 12, "coursework": 75, "practical": 13}, "modules": ["Electrocardiogram (ECG) Interpretation for Paramedic Practice", "Interpersonal Skills for Paramedic Practice", "Life Sciences for Paramedic Practice", "Medical Conditions Emergency Care", "Paramedic Practice 1", "Principles of Prehospital Emergency Care", "Advanced Life Support Skills", "Emergency Care of the Child", "Emergency Care of the Older Adult", "Evidence Based Paramedic Practice", "Paramedic Practice 2", "Psychosocial Aspects of Paramedic Practice", "Trauma and Mass Casualty Management", "Applied Paramedic Pharmacology", "Evolving Paramedic Practice", "Law, Ethics and Leadership in Paramedic Practice", "Paramedic Practice 3", "Primary and Urgent Care Within Paramedic Practice"]},
        {"major": "Philosophy", "introduction": "Study a future-facing, interdisciplinary philosophy degree, where you'll focus on applying theory to practice. Your teaching will be centred around core themes, comprising of: Health, Society and Public Ethics; Technology, Environment and Sustainability; and Human Flourishing and Creative Practice.", "assessment": {"exams": 32, "coursework": 63, "practical": 5}, "modules": ["Ancient Philosophy - introduces you to the most significant authors, texts, and issues of Ancient Greek Philosophy, from its origin to Aristotle, stressing the unitary character of its metaphysical, ethical, and political breakthroughs.", "Existentialism and Questions of Human Nature - aims to ground you in the importance of understandings of the human in the 18th and 19th century and the influence of these debates on 20th-century existentialism and its consideration of moral agency and freedom.", "Philosophical Methods: Introduction - provides an introduction to the key skills required for the assessment and construction of philosophical arguments, and therefore provides a set of core skills you will build on throughout the course. The module also gives you a critical introduction to various philosophical theories of knowledge.", "Understanding our Global and Social Environment - prepares you for the global social/political, technological, and environmental themes that you will encounter throughout the course.", "Philosophical Methods - introduces you to the processes and methods used to produce knowledge and disseminate research in philosophy, in particular to non-academic audiences.", "Self and Society - brings together philosophical theories and skills with practice, enabling you to reflect on and apply the skills and experience that you gain throughout this philosophy degree.", "Philosophy Project and Placement - builds on the knowledge you've acquired across the course and allows you to demonstrate a systematic understanding of key aspects of philosophy, including acquisition of coherent and detailed understanding which is informed by knowledge at the forefront of philosophy. You will also demonstrate critical skills in the development of your own arguments and positions."]},
        {"major": "Photography", "introduction": "This course is affiliated with the leading professional body for photographers in the UK and beyond, the Association of Photographers. Our facilities include a fleet of full-frame DSLR cameras, 10x8, 5x4, and medium format analogue cameras, medium format digital equipment, lighting kits, and fully equipped analogue and digital darkrooms, along with seven separate studio spaces.", "assessment": {"exams": 33, "coursework": 33, "practical": 34}, "modules": ["Exploring Practice in Photography 1", "Photographic Foundations", "Exploring Practice in Photography 2", "Introduction to Professional Practice in Photography", "Developing Practice in Photography 1", "Photography in Context", "Enterprise and Marketing in Photography", "Extended Study in Photography 1", "Independent Research Study in Photography", "Extended Study in Photography 2", "Career Strategies for Photography"]},
        {"major": "Physiotherapy", "introduction": "Once you have graduated you can apply for registration with the Health and Care Profession Council, a pre-requisite for working as a physiotherapist. You will also be eligible to apply for membership of the Chartered Society of Physiotherapy.", "assessment": {"exams": 18, "coursework": 28, "practical": 54}, "modules": ["Physiotherapy Practice 1: Essential Skills", "Clinical Anatomy and Kinesiology for Physiotherapy and Sport Rehabilitation", "Fundamentals of Human Anatomy and Physiology", "Essentials of Musculoskeletal Physiotherapy", "Essentials of Neuroscience for Physiotherapy", "Essentials of Respiratory Physiotherapy", "Physiotherapy Practice 2b", "Informing Practice through Research and Inquiry", "Physiotherapy Across the Lifespan", "Clinical Reasoning for Musculoskeletal Physiotherapy and Practice 2a", "Clinical Reasoning for Neurological Physiotherapy", "Clinical Reasoning for Cardiorespiratory Physiotherapy", "Physiotherapy Practice 3", "Research and Evidence in Practice", "Healthy Futures", "Consolidation of Learning into Practice", "Complex Clinical Reasoning for Neurological and Musculoskeletal Physiotherapy", "Complex Clinical Reasoning: Management of the Critically Ill Patient"]},
        {"major": "Politics and International Relations", "introduction": "BA(Hons) Politics and International Relations at UWE Bristol is an applied, future-focused course, which emphasises the importance of theory, policy, and practice in political and global affairs.", "assessment": {"exams": 28, "coursework": 61, "practical": 11}, "modules": ["Critical Thinking and Political Theory", "International Relations", "Politics of Crisis and Change", "Politics, States and Resistance", "Political Innovation, Leadership and Communication", "Politics and International Relations Project and Placement"]},
        {"major": "Product Design", "introduction": "Learn from tutors and professionals with extensive design experience and graduate ready to join industry or start your own creative venture.", "assessment": {"exams": 6, "coursework": 83, "practical": 11}, "modules": ["Product Design Studio 1", "Design Communication", "Objects and Experiences", "Graphic Design", "Design in Context", "Creative Product Design Studio 2", "Product CAD", "Engineering for Designers", "Aesthetics and Product Language", "Materials and Processes", "Individual Project Product Design", "Product Design Studio 3", "Design Research Methods", "Design Futures"]},
        {"major": "Product Design Technology", "introduction": "Learn how to design great products on a friendly and creative course with tutors who are highly experienced professional designers.", "assessment": {"exams": 7, "coursework": 81, "practical": 12}, "modules": ["Design Communication", "Design in Context", "Graphic Design", "Mechanisms and Structures", "Product Design Studio 1", "Materials and Processes", "Physical Computing", "Product CAD", "Product Design Engineering", "Product Design Technology Studio 2", "Design in Practice", "Design Research Methods", "Individual Project (Product Design)", "Innovation, Technology and Design", "Product Design Studio 3"]},
        {"major": "Professional Policing", "introduction": "UWE Bristol are regional pioneers of the national transformation in police education. We are licensed by the College of Policing to offer the Pre-join Degree in Professional Policing. This course will prepare you to apply for a role in one of 43 UK police forces.", "assessment": {"exams": 60, "coursework": 20, "practical": 20}, "modules": ["Core Policing Functions: Culture and Structure", "Core Policing Functions: Legislation and Powers", "Introduction to Evidence-based Policing", "Investigating Crime", "Principles of Equality, Diversity and Inclusivity", "Volume and Priority Crime", "Analysing Police Trends", "Core Policing Functions: Communities and Partnerships", "Public Protection", "Revealing Risk and Vulnerability", "Serious and Organised Crime", "Supporting Victims and Witnesses", "Creating Change in the Criminal Justice System", "Digital Policing", "Ethical Policing: Conduct, Challenges, Consequences", "Evidence-Based Research Project", "Policing Threats"]},
        {"major": "Psychology", "introduction": "This course is accredited by the British Psychological Society and has a strong practical focus that will build your professional skills, enhance your CV and get you noticed by employers.", "assessment": {"exams": 37, "coursework": 57, "practical": 6}, "modules": ["Introduction to Psychology", "Research Design and Analysis 1", "Psychology in Action", "Critical Thinking (Psychology)", "Interpersonal Psychology", "Research Design and Analysis 2", "Identities in Psychology", "Mind, Brain and Development", "Developing Self and Society", "Psychology Project"]},
        {"major": "Quantity Surveying and Commercial Management", "introduction": "Gain a strong start to your professional career with accreditation from the Chartered Institute of Building (CIOB) (subject to conditions), Royal Institution of Chartered Surveyors (RICS) and Chartered Institute of Civil Engineering Surveyors (ICES).", "assessment": {"exams": 41, "coursework": 53, "practical": 6}, "modules": ["Quantity Surveying Practice and Procedures", "Law, Economics and Management", "Environmental Physics and Materials", "Construction Technology and Services", "Quantity Surveying Project", "Procurement and Contract Practice", "Construction Technology and Building Services", "Development and Design Economics", "Professional Practice for the Built Environment", "International Cost Management", "Commercial Management", "Innovation and Professionalism", "Dissertation"]},
        {"major": "Radiotherapy and Oncology", "introduction": "This course is approved by the Health and Care Professions Council (HCPC) so you will be eligible to apply for registration with them when you graduate.", "assessment": {"exams": 24, "coursework": 59, "practical": 17}, "modules": ["Fundamentals of Human Anatomy and Physiology (Radiotherapy and Oncology) - Physical Sciences and Imaging Technology 1", "Introduction to Oncology and Radiotherapy", "Clinical Context and Applications to Radiotherapy 1", "Patient Care and Clinical Radiotherapy Practice", "Professional Behaviour and Health Psychology", "Clinical Context and Applications to Radiotherapy 2", "Intermediate Oncology and Radiotherapy Studies", "Principles of Radiotherapy Planning and Simulation", "Professional Development and Radiotherapy Clinical Practice", "Informing Practice Through Research and Inquiry (Radiotherapy and Oncology)", "Clinical Radiotherapy Practice 3", "Healthy Futures", "Research and Evidence in Practice (Radiotherapy and Oncology)", "Progression to Autonomous Radiotherapy Practice", "Communication Skills in Radiotherapy and Cancer Care"]},
        {"major": "Real Estate", "introduction": "Study towards Chartered Surveyor status on a course with close employer links that gives you the flexibility to go into a wide range of careers.", "assessment": {"exams": 51, "coursework": 39, "practical": 10}, "modules": ["Healthy Sustainable Communities", "Introduction to Building Construction", "Introduction to Valuations", "Law, Economics and Management", "Development Appraisal and Planning", "Examination and Evaluation of Existing Buildings", "Investment Valuation and Appraisal", "Landlord and Tenant", "Professional Practice for the Built Environment", "Rating and Taxation", "Real Estate Economics", "Dissertation A", "International Property Management and Investment", "Property Transactions and Technology", "Valuations"]},
        {"major": "Robotics", "introduction": "Learn in the world-renowned Bristol Robotics Laboratory, using our state-of-the-art equipment to make and test your own inventions.", "assessment": {"exams": 36, "coursework": 59, "practical": 5}, "modules": ["Engineering Practice 1", "Mathematical Modelling for Electronics and Robotics", "Fundamental Robotics Principles", "Applied Electronics", "Programming for Engineers", "Engineering Research", "Microcontroller Applications Group Lab", "Robot Control Systems", "Signal Theory", "Introduction to Machine Vision", "Engineering Project", "Group Design and Integration Project", "Advanced Vision for Localisation and Mapping", "Human Robot Interaction Technologies", "Professionalism for Engineers"]},
        {"major": "Social Work", "introduction": "Social work changes lives. Our BSc(Hons) Social Work course enables you to become a qualified social worker and develop the understanding and skills to support society's most vulnerable people to ensure their wellbeing.", "assessment": {"exams": 16, "coursework": 72, "practical": 12}, "modules": ["Law for Social Work Practice", "Readiness for Professional Social Work Practice", "Relationship Based Social Work", "Rethinking Social Justice: Social Policy and Inequalities", "Social Work and the Life Course", "Engaging with Young People, Children and Families", "Mental Health, Society and Social Work", "Social Work Placement 1", "Working with Adults in Social Work Practice", "Equality, Ethics and Values for Social Work", "Future Practice; Leadership, Organisations and Sustainability", "Research Proposal Project", "Risk, Complexity and Decision-Making", "Social Work Placement 2"]},
        {"major": "Sociology", "introduction": "Get to the heart of the issues facing society today by taking placements or internships, working with leading experts and developing your own insights into how to make a difference.", "assessment": {"exams": 18, "coursework": 65, "practical": 17}, "modules": ["Foundations in Social Theory", "Social Issues and Social Problems", "Comparing Cultures", "Sociological Practice - Becoming a Social Scientist", "Critical Thinking (Sociology and Criminology)", "Theorising Social Life", "Nature and Use of Research (Sociology)", "Developing Self and Society (Sociology)", "Sociology Project and Placement Module"]},
        {"major": "Software Engineering for Business", "introduction": "Developed by TechSkills and top graduate employers, this course will give you the practical, real-world skills you need to succeed in your career.", "assessment": {"exams": 27, "coursework": 54, "practical": 19}, "modules": ["IT Practice: Skills, Models and Methods", "Introduction to OO Systems Development", "Foundations of Computing", "Information Systems Development", "IT Practice: Collaborative Project", "Data Schemas and Applications", "Object-Oriented Systems Development", "Design and Analysis of Data Structures and Algorithms", "IT Practice: Consultancy Project", "Ethical and Professional Issues in Computing and Digital Media", "Software Development Project", "Development of Information Systems Projects"]},
        {"major": "Sport Rehabilitation", "introduction": "Hit the ground running as a sport rehabilitator, on this British Association of Sport Rehabilitators and Trainers-accredited course.", "assessment": {"exams": 4, "coursework": 33, "practical": 63}, "modules": ["Fundamentals of Human Anatomy and Physiology", "Clinical Anatomy and Kinesiology for Physiotherapy and Sport Rehabilitation", "Sport Rehabilitation Practice 1", "Foundations of Exercise Prescription", "Epidemiology and Aetiology of Sports Injuries", "Supporting Healthy Lifestyles with Physical Activity", "Sport Rehabilitation Practice 2", "Informing Practice Through Research and Inquiry", "Applied Athlete Conditioning and Sports Nutrition", "Athletic Therapy and Functional Rehabilitation", "Research and Evidence in Practice", "Exercise Prescription for Special Populations", "Advanced Practice of Sport Rehabilitation", "Healthy Futures", "Sport Rehabilitation Practice 3"]},
        {"major": "Sports Business and Entrepreneurship", "introduction": "This ground-breaking course, run by Bristol City Robins Foundation at Bristol City Football Club, offers three years of hands-on experience in setting up and running your own business alongside your studies.", "assessment": {"exams": 0, "coursework": 72, "practical": 28}, "modules": ["Running a Learning Organisation 1", "Managing My Learning and Development 1", "Enterprising and Entrepreneurial Practice 1", "Enquiry into Enterprise and Entrepreneurship 1", "Running a Learning Organisation 2", "Managing My Learning and Development 2", "Enterprising and Entrepreneurial Practice 2", "Enquiry into Enterprise and Entrepreneurship 2", "Running a Learning Organisation 3", "Managing My Learning and Development 3", "Enterprising and Entrepreneurial Practice 3", "Enquiry into Enterprise and Entrepreneurship 3"]},
        {"major": "Urban Planning", "introduction": "This course, accredited by the Royal Town Planning Institute (RTPI) as a spatial degree, boasts high levels of student satisfaction and employability.", "assessment": {"exams": 32, "coursework": 53, "practical": 15}, "modules": ["Healthy Sustainable Communities", "Law, Economics and Management", "People and Planning", "People, Places and Change", "Professional Development and Practice", "Development Appraisal and Planning", "Development, Practice and Law", "Future Places", "Professional Experience", "Researching the City", "Achieving Design Quality", "Final Year Project*", "Independent Project**", "Infrastructure Design and Implementation Project", "Planning Global Cities", "Planning Theory"]},
        {"major": "Wildlife Ecology and Conservation Science", "introduction": "Immerse yourself in the scientific study of wildlife with this specially-developed degree, crafted in collaboration with Bristol Zoo Project.", "assessment": {"exams": 28, "coursework": 59, "practical": 13}, "modules": ["Life on Earth", "The Earth", "Field Skills (includes residential field trip, where possible)", "Wildlife and Society", "Environmental and Field Techniques (includes residential trip, where possible)", "Conservation in Practice", "Ecology and Ecosystem Protection", "Research Dissertation Project", "Contemporary Conservation Science"]}
      ]

        # Process majors data and apply the TF-IDF and cosine similarity
        preprocessed_majors = [remove_stopwords(major['introduction']) for major in majors_data]

        # Calculate TF-IDF and cosine similarity
        tfidf_vectorizer = TfidfVectorizer()
        tfidf_matrix = tfidf_vectorizer.fit_transform([preprocessed_likes, preprocessed_dislikes] + preprocessed_majors)

        likes_vector = tfidf_vectorizer.transform([preprocessed_likes])
        dislikes_vector = tfidf_vectorizer.transform([preprocessed_dislikes])

        likes_similarity = cosine_similarity(likes_vector, tfidf_matrix)[0][2:]  # Skip the first two (self and dislikes)
        dislikes_similarity = cosine_similarity(dislikes_vector, tfidf_matrix)[0][2:]  # Skip the first two (self and likes)

        adjusted_similarity = likes_similarity - dislikes_similarity  # Simple penalty mechanism

        # Filter and format the results
        adjusted_results = [
            (majors_data[i]["major"], round(adjusted_similarity[i], 2)) 
            for i in range(len(majors_data)) 
            if adjusted_similarity[i] > 0
        ]
        adjusted_results.sort(key=lambda x: x[1], reverse=True)

        # Pass the top 10 results
        return render_template_string(HTML_TEMPLATE, results=adjusted_results[:10])
    return render_template_string(HTML_TEMPLATE, results=[])

if __name__ == '__main__':
    app.run(debug=True)
